set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C2C1C3 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C2C1C3 guibg=#0A060E guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#914CA4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#6E6576 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#8F8994 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#5F5568 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#914CA4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#0A060E guibg=#C2C1C3 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#6E6576 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#8F8994 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#B14379 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#C03062 guibg=NONE guisp=#C03062 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#649ED8 guibg=NONE guisp=#649ED8 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#B644CF guibg=NONE guisp=#B644CF blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#303CC0 guibg=NONE guisp=#303CC0 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#256298 guibg=#5F5568 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#7E7486 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#C03062 guibg=#5F5568 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#C03062 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#B644CF guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#256298 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#B644CF guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C2C1C3 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#C03062 guibg=#C2C1C3 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#C03062 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#914CA4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#B644CF guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#5F5568 guibg=#914CA4 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C2C1C3 guibg=#0A060E guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#7E7486 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C2C1C3 guibg=#7E7486 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#5F5568 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#B644CF guibg=NONE guisp=#7E7486 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#8F8994 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C2C1C3 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#B14379 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#B14379 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#303CC0 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#6E6576 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#0A060E guibg=#649ED8 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#0A060E guibg=#B644CF guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#0A060E guibg=#256298 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#0A060E guibg=#E59AA1 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#0A060E guibg=#C03062 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#0A060E guibg=#914CA4 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#5F5568 guibg=#914CA4 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#7E7486 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#256298 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#6E6576 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#7E7486 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#C03062 guibg=#C2C1C3 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#7E7486 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#914CA4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#C2C1C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C2C1C3 guibg=#B644CF guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#6E6576 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C2C1C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#7E7486 guibg=#303CC0 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#6E6576 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#B14379 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#7E7486 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#C03062 guibg=NONE guisp=#C03062 blend=NONE gui=underline
highlight SpellCap guifg=#303CC0 guibg=NONE guisp=#303CC0 blend=NONE gui=underline
highlight SpellLocal guifg=#649ED8 guibg=NONE guisp=#649ED8 blend=NONE gui=underline
highlight SpellRare guifg=#E59AA1 guibg=NONE guisp=#E59AA1 blend=NONE gui=underline
highlight Statement guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#8F8994 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#6E6576 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#3B8CCE guibg=#256298 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#5C66D6 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#7E7486 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#7E7486 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#256298 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#303CC0 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#8F8994 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#0A060E guibg=#6E6576 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C2C1C3 guibg=#B644CF guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#8F8994 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#6E6576 guibg=#0A060E guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#B14379 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#8F8994 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C2C1C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C2C1C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C2C1C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C2C1C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#89B4E1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#B14379 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#256298 guibg=#5F5568 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#C03062 guibg=#5F5568 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#E59AA1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#256298 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#649ED8 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#303CC0 guibg=#5F5568 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#5F5568 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#B644CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#303CC0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#C03062 guibg=NONE guisp=NONE blend=NONE gui=NONE
